---
- name: Install Web package
  hosts: web
  gather_facts: yes

  tasks:
    - name: Display facts
      debug:
        msg:
          - "{{ ansible_distribution }}"
          - "{{ ansible_memfree_mb }}"

    - name: Install web package
      package:
        name: "{{ web_pkg }}"
        state: latest
      when:
        (ansible_distribution == "CentOS" and ansible_memfree_mb > 256)
        or
        (ansible_distribution == "Ubuntu" and ansible_memfree_mb > 256)
      

# logical AND - if a list of conditions are specified
# adhoc command to check facts
# ansible lamp -m setup -a "filter=ansible_distribution"
# ansible lamp -m setup -a "filter=ansible_memfree_mb"