---
- name: Restart sshd service only if crond is running
  hosts: file1
  gather_facts: no

  tasks:
    - name: Start / Stop crond service
      service:
        name: crond
        state: started
        # state: stopped

    - name: Get status of crond service
      command:
        cmd: systemctl is-active crond
      ignore_errors: yes
      register: result

    - name: Display the result
      debug:
        var: result

    - name: Restart sshd if crond is running
      service:
        name: sshd
        state: restarted
      when: result.rc == 0
      

