---
- name: Demonstrate register and failed_when
  hosts: web1
  gather_facts: no

  tasks:
    - name: Run a CLI command
      command: echo hello world
      register: command_result
    
    - name: Display registered variable
      debug:
        var: command_result

    - name: Simulate task failure
      debug:
        msg: FAILED
      ignore_errors: yes
      failed_when: "'world' in command_result.stdout"

    - name: Task followd by a FAILED task
      debug:
        msg: Task executed


# register the output of tasks and examine it

# Playbook execution is terminated when a task fails
# Subsequent tasks will not run

# If further tasks are to be run even when the previous task fails
# ignore_errors: yes

