---
- name: Demonstrate WHEN conditional
  hosts: file
  gather_facts: yes

  tasks:
    - name: Display mount points from gathered facts
      debug:
        # var: ansible_facts
        var: ansible_mounts

    - name: Install & update FTP package (if atlease 100MB is available at /)
      yum:
        name: vsftpd
        state: latest
      when: item.mount == '/' and item.size_available > 100000000
      loop: "{{ ansible_mounts }}"
      loop_control:
        label: "{{ item.mount }}"
      



# when - make the task conditional
# - check something on
# - previously declared / registered variables
# - discovered facts
# The task is skipped if 'when' condition is not met
# Operators for 'when'
# x == y
# x != y
# x > y
# x >= y
# x < y
# x <= y
# x is y (failed, succeeded, defined, undefined)
# x in y
# x (Boolean True)
# not x (Boolean False)
# read string as integer
# version | int 
# combine multiple conditions with `and` or `or`